language: node_js
branches:
  only:
    - master
    - monorepo
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 8
script:
  - yarn test
  - yarn build
after_success:
  - yarn report-coverage
  - yarn release
